apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: predictive-inference-hpa
  namespace: darip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: darip-predictive-inference
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-ingestion-hpa
  namespace: darip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: darip-data-ingestion
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
